print("----------------------------------")
print("    Godlike Shop VAT INVOICE")
print("----------------------------------")
print("Water     X 1  :  10 THB")
print("Banana    X 1  :  12 THB")
print("Chocolate X 1  :  25 THB")
print("Latae     X 1  :  120 THB")
print("Caramel   X 1  :  50 THB")
print("----------------------------------")
print("Total          :  217 THB")